import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./AppComponents/Navbar";
import SessionDataProvider from "./Providers/SessionDataProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-screen w-screen ${inter.className}`}>
        <SessionDataProvider>
        <Navbar />{children}
        </SessionDataProvider>

        </body>
    </html>
  );
}
